const SUPABASE_URL = "https://vjalivzqoiqnuadbkrce.supabase.co";

const SUPABASE_KEY =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqYWxpdnpxb2lxbnVhZGJrcmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxMTI5NDMsImV4cCI6MjA5NTY4ODk0M30.nIh-u0GHpQkBPQWLN7UKETagAJOoaIbVml3TCtEJpoE";

const TREASURY_WALLET =
"4WPDwwnQGitn9kmWZqwRBefcFMMCDTCgS2TPZ2ZSMK5u";

const MIN_CLAIM_AMOUNT = 1.00;